/**
 * What a session was ABOUT, derived from its transcript.
 *
 * A session list that reads "claude-opus-5 · eMachina · 12:12" nine times over
 * cannot be scanned: every column is constant across the rows you are trying to
 * tell apart. The one thing that distinguishes them is what was asked, and that
 * is in the transcript — but not on its first line.
 *
 * The first user-role step is almost never the ask. Measured on the live index,
 * the real ask sat at user step 7 on one session, behind: a `<system-reminder>`
 * block, a continuation preamble, a "file was read before the last conversation
 * was summarized" note, two slash commands and their stdout. So this is a
 * SKIP-list problem, not a "take the first" problem, and the skip list is
 * written from observed traffic rather than guessed.
 *
 * Kept in one module, and unit-tested, because the same rule has to serve the
 * session list, the session header and the recent-sessions strip; three copies
 * of a heuristic is three places for it to drift.
 */

/**
 * Prefixes that mark a user-role step as harness chatter rather than a human
 * asking for something. Matched against the UNWRAPPED text (see `unwrap`),
 * case-insensitively, after leading whitespace is removed.
 */
const NOISE_PREFIXES = [
  "<system-reminder>",
  "<transcript>",
  "<command-name>",
  "<local-command-stdout>",
  "<command-message>",
  // Wraps the slash-command block above, and is a SEPARATE step from it — so
  // the tag has to be skipped on its own. Titled 5 of 86 live sessions
  // "Caveat: The messages below were generated by the user…" before it was
  // listed, which is the harness telling the model to ignore what follows.
  "<local-command-caveat>",
  // Background-task wake-ups. The text says "NOT USER INPUT" in its first line
  // and titled 3 more sessions.
  "[system notification - not user input]",
  "## exited plan mode",
  "this session is being continued from a previous conversation",
  "note: ", // "Note: <path> was read before the last conversation was summarized"
  "critical: respond with text only",
  "the task tools haven't been used recently",
  "the following is the user's claude.md configuration",
  "caveat: the messages below were generated by the user while running local commands",
  "<analysis>",
  // A mid-turn interjection Claude Code splices in ("The user sent a new
  // message while you were working: …"). The words after it ARE the user's,
  // but they are an aside inside a running turn, not the ask that session
  // exists to answer — one such session would have been titled "proud of you!".
  "the user sent a new message while you were working",
  // Emitted into the parent's transcript when a subagent returns.
  "subagent has finished and is handing back control",
  "<user-prompt-submit-hook>",
  // Written when a turn is cancelled. It is the HARNESS narrating the cancel,
  // not the user, and it titled 2 of 82 live main-thread sessions — in both
  // cases burying a real ask that came a few steps later ("you should be
  // searching in the filesystem as well…").
  "[request interrupted by user]",
  // Claude Code's own next-prompt suggestion scaffolding.
  "[suggestion mode:",
  // A WebFetch result echoed back as a user message; titled 1 session
  // "Web page content: --- > ## Documentation Index > Fetch the complete…".
  "web page content:",
];

/**
 * The output-style banner Claude Code re-injects on nearly every turn
 * ("Learning output style is active. Remember to follow the specific guidelines
 * for this style."). Matched on the frame rather than listed per style, because
 * the set of styles is open — a custom style would otherwise slip through. It
 * titled 2 of 82 live main-thread sessions, and appeared 4+ times in one.
 *
 * Tested CASE-SENSITIVELY, like {@link HOOK_OUTPUT}: the style name is
 * capitalized, and that capital is the only thing separating this from a person
 * writing "the output style is active but wrong, please fix".
 */
const OUTPUT_STYLE_BANNER = /^[A-Z][\w -]* output style is active\b/;

/**
 * A mid-turn interjection, and the words the user actually typed inside it.
 *
 * Claude Code splices these in as
 * `The user sent a new message while you were working: <words>` followed by a
 * paragraph of explanation addressed to the model. Capturing group 1 is the
 * user's own text with that trailing explanation removed.
 */
const INTERJECTION =
  /^the user sent a new message while you were working:\s*([\s\S]*?)(?:\s*this is how claude code surfaces|$)/i;

/**
 * Injected-file preambles. Claude Code splices rules and CLAUDE.md files into
 * the transcript as user messages shaped `Contents of <abs-path>: …`, which is
 * configuration being handed to the agent, not a person asking for something.
 * Matched as a pattern rather than a prefix so an ask that merely opens with
 * the words "contents of" is untouched.
 */
const INJECTED_FILE = /^contents of \/\S+\s*:/;

/**
 * Replayed tool traffic. After a compaction Claude Code re-narrates the tools
 * it called as user-role prose ("Called the Read tool with the following
 * input: …"), which titled 2 of 86 live sessions with a file path. Matched on
 * the whole "<verb> the <Tool> tool" frame so a person writing "called the
 * shots" is untouched.
 */
const TOOL_ECHO = /^(called|result of calling) the \S+ tool\b/;

/**
 * Hook stdout spliced into the transcript as a user message —
 * "UserPromptSubmit hook additional context: …", "SessionStart hook success: …".
 * Matched on the `<Event> hook <outcome>` frame rather than listing every event
 * and outcome pair, because the set of hook events grows.
 *
 * Tested CASE-SENSITIVELY against the original text, not the lowercased copy:
 * the event name is CamelCase, and that is the only thing separating this from
 * a person writing "the hook additional context is wrong, please fix" — which
 * a case-blind `\w+ hook` swallowed.
 */
const HOOK_OUTPUT = /^[A-Z][A-Za-z]+ hook (success|failed|additional context)\b/;

/**
 * Claude Code's own title-generation call: the conversation it is naming is
 * wrapped in `<session>…</session>` and followed by instructions to the model
 * ("Write the title in the predominant language…").
 *
 * The wrapper is scaffolding but its CONTENTS are the genuine ask — this is the
 * one envelope worth opening rather than skipping, and it is why unwrapping
 * happens before the noise test rather than after.
 */
const SESSION_WRAP = /^<(session|conversation)>([\s\S]*?)<\/\1>/i;

/**
 * A step that is several JSON envelopes concatenated — `{"Bash":"…"} {"user":
 * "…"}` — is a serialized transcript being handed to an auxiliary call (a
 * permission check, a title generation), not a person typing.
 *
 * Detected by "looks like JSON but does not parse as ONE object": a real user
 * message that happens to open with `{"` is vanishingly rare, and a transcript
 * dump never parses whole. Titling by it produced rows reading
 * `{"user":"<command-name>/model</command-name>…` in the sessions list.
 */
function isTranscriptDump(trimmed: string): boolean {
  if (!trimmed.startsWith('{"')) return false;
  try {
    const parsed = JSON.parse(trimmed);
    return !parsed || typeof parsed !== "object";
  } catch {
    return true;
  }
}

/** A step whose whole body is one of these tags carries no ask. */
// Both halves of the transcript wrapper arrive as steps of their own.
const NOISE_EXACT = new Set(["<transcript>", "</transcript>", ""]);

/**
 * Unwrap the one-key JSON envelope transcript steps are stored in.
 *
 * User-side steps arrive as `{"user": "..."}` for something a person typed and
 * `{"<ToolName>": "..."}` for a tool result being fed back. Only the `user`
 * key can hold an ask; a `{"Bash": "..."}` step is the previous turn's output,
 * which is why tool-keyed envelopes are rejected outright rather than searched.
 */
function unwrap(raw: string): { text: string; isToolResult: boolean } {
  const trimmed = raw.trim();
  const wrapped = SESSION_WRAP.exec(trimmed);
  // Opened, not skipped: what a title-generation call wraps IS the ask.
  if (wrapped) return { text: wrapped[2].trim(), isToolResult: false };
  if (isTranscriptDump(trimmed)) return { text: "", isToolResult: true };
  if (!trimmed.startsWith("{")) return { text: trimmed, isToolResult: false };
  let parsed: unknown;
  try {
    parsed = JSON.parse(trimmed);
  } catch {
    return { text: trimmed, isToolResult: false };
  }
  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
    return { text: trimmed, isToolResult: false };
  }
  const keys = Object.keys(parsed as Record<string, unknown>);
  if (keys.length !== 1) return { text: trimmed, isToolResult: false };
  const value = (parsed as Record<string, unknown>)[keys[0]];
  if (typeof value !== "string") return { text: trimmed, isToolResult: false };
  return { text: value.trim(), isToolResult: keys[0] !== "user" };
}

/** True when this user-step text is harness chatter rather than an ask. */
export function isNoiseStep(raw: string): boolean {
  const { text, isToolResult } = unwrap(raw);
  if (isToolResult) return true;
  const lower = text.toLowerCase();
  if (NOISE_EXACT.has(lower)) return true;
  if (INJECTED_FILE.test(lower)) return true;
  if (TOOL_ECHO.test(lower)) return true;
  if (OUTPUT_STYLE_BANNER.test(text)) return true;
  if (HOOK_OUTPUT.test(text)) return true;
  return NOISE_PREFIXES.some((p) => lower.startsWith(p));
}

/**
 * The user's own words out of a mid-turn interjection, or "" if this step is
 * not one.
 *
 * Interjections stay on the noise list for the FIRST pass — an aside inside a
 * running turn is not the ask a session exists to answer, and preferring one
 * would have titled a session "proud of you!". But when a session contains no
 * standalone ask at all, the aside is the only human text in it, and "the user
 * typed this, mid-turn" beats an empty row. Two of 82 live main-thread sessions
 * are titled only by this, and both had been showing
 * "[Request interrupted by user]" or nothing.
 */
export function interjectionText(raw: string): string {
  const { text, isToolResult } = unwrap(raw);
  if (isToolResult || !text) return "";
  const m = INTERJECTION.exec(text);
  return m ? m[1].trim() : "";
}

/**
 * A role-assignment preamble: "You are an INDEPENDENT REVIEWER for PR #390 in
 * the repo at /Users/sp/Documents/git/eMachina (GitHub:…".
 *
 * These ARE the ask — a `claude -p` run is driven by one, and 9 of 82 live
 * main-thread sessions open with one — but only the opening clause carries the
 * job. The rest is setup, and at 120 characters it crowds the job out entirely:
 * six sessions read identically as "You are running the `curate` skill, which
 * is at ./skill/SKILL.md (read it and its refe…". Clipped to the first sentence
 * they become distinguishable again.
 */
const ROLE_PROMPT = /^you are\b/i;

/**
 * How much of a role prompt to keep. Only applies when the prompt has no
 * sentence break to cut at — a complete opening sentence is kept whole because
 * it already names the job ("You are summarizing a Claude Code session for a
 * daily memory log."). Without one, a tighter clip is what pulls the
 * distinguishing part into view: at 120 characters six `curate` runs read
 * identically, at 64 they do not.
 */
const ROLE_TITLE_MAX = 64;

/** Clip a role prompt to its opening sentence, or failing that, tightly. */
function roleTitle(text: string, max: number): string {
  const end = /[.?!](?:\s|$)/.exec(text);
  // The offset floor keeps an abbreviation in the first few words ("You are
  // Dr. Foo's reviewer") from cutting the title down to nothing.
  if (end && end.index >= 12) return clipTitle(text.slice(0, end.index + 1), max);
  return clipTitle(text, Math.min(max, ROLE_TITLE_MAX));
}

/** Collapse to one line and clip on a word boundary where one is near. */
export function clipTitle(text: string, max = 120): string {
  const flat = text.replace(/\s+/g, " ").trim();
  if (flat.length <= max) return flat;
  const cut = flat.slice(0, max);
  const space = cut.lastIndexOf(" ");
  // Only respect the word boundary when it is not throwing away a third of the
  // budget; otherwise a long unbroken token would clip to almost nothing.
  return (space > max * 0.6 ? cut.slice(0, space) : cut) + "…";
}

/**
 * The session's title: the first user step that is an actual ask.
 *
 * Resolved in two passes, best evidence first:
 *
 *  1. The first standalone ask — a user step that survives the noise skip list.
 *  2. Failing that, the first mid-turn interjection's text. Still the user's
 *     own words, just spliced into a running turn rather than opening one.
 *
 * @param userMessages raw `message` column values for the session's user-role
 *   steps, in transcript order.
 * @returns the clipped ask, or `""` when the session contains no human text at
 *   all — a real state (a permission-hook fan-out records one shared
 *   instruction and nothing typed) that must not be papered over with an
 *   invented placeholder. Measured on 82 live main-thread sessions: 75 resolve
 *   in pass 1, 2 in pass 2, 5 genuinely have nothing.
 */
export function sessionTitle(userMessages: string[], max = 120): string {
  for (const raw of userMessages) {
    if (!raw || isNoiseStep(raw)) continue;
    const { text } = unwrap(raw);
    if (!text) continue;
    return ROLE_PROMPT.test(text) ? roleTitle(text, max) : clipTitle(text, max);
  }
  for (const raw of userMessages) {
    if (!raw) continue;
    const said = interjectionText(raw);
    if (said) return clipTitle(said, max);
  }
  return "";
}

/**
 * What a session DID, for the sessions that contain nothing anyone typed.
 *
 * Six of 82 live main-thread sessions have no human text at all — a rescue
 * sweep that is 82 steps of `Bash` and `mcp__emachina__get`, a hook fan-out
 * carrying one shared instruction. "untitled session" says only that the title
 * lookup failed; the tool mix says what the session was actually for, and it is
 * measured rather than invented.
 *
 * Deliberately NOT sentence-shaped — `Bash ×34 · Read ×12` cannot be mistaken
 * for something a person asked for, which is the whole reason a placeholder was
 * refused here in the first place.
 *
 * @returns the top tools by call count, or `""` when the session called none —
 *   at which point there genuinely is nothing to say.
 */
export function activityTitle(
  toolHistogram: Record<string, number> | undefined,
  topN = 3,
): string {
  const tools = Object.entries(toolHistogram ?? {})
    .filter(([name, n]) => name && Number(n) > 0)
    // Count first, then name, so the label is stable across equal counts.
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .slice(0, topN);
  if (!tools.length) return "";
  return tools.map(([name, n]) => `${name} ×${n}`).join(" · ");
}
