/**
 * What a session was ABOUT, derived from its transcript.
 *
 * A session list that reads "claude-opus-5 · eMachina · 12:12" nine times over
 * cannot be scanned: every column is constant across the rows you are trying to
 * tell apart. The one thing that distinguishes them is what was asked, and that
 * is in the transcript — but not on its first line.
 *
 * The first user-role step is almost never the ask. Measured on the live index,
 * the real ask sat at user step 7 on one session, behind: a `<system-reminder>`
 * block, a continuation preamble, a "file was read before the last conversation
 * was summarized" note, two slash commands and their stdout. So this is a
 * SKIP-list problem, not a "take the first" problem, and the skip list is
 * written from observed traffic rather than guessed.
 *
 * Kept in one module, and unit-tested, because the same rule has to serve the
 * session list, the session header and the recent-sessions strip; three copies
 * of a heuristic is three places for it to drift.
 */

/**
 * Prefixes that mark a user-role step as harness chatter rather than a human
 * asking for something. Matched against the UNWRAPPED text (see `unwrap`),
 * case-insensitively, after leading whitespace is removed.
 */
const NOISE_PREFIXES = [
  "<system-reminder>",
  "<transcript>",
  "<command-name>",
  "<local-command-stdout>",
  "<command-message>",
  "## exited plan mode",
  "this session is being continued from a previous conversation",
  "note: ", // "Note: <path> was read before the last conversation was summarized"
  "critical: respond with text only",
  "the task tools haven't been used recently",
  "the following is the user's claude.md configuration",
  "caveat: the messages below were generated by the user while running local commands",
  "<analysis>",
  "<user-prompt-submit-hook>",
];

/**
 * Injected-file preambles. Claude Code splices rules and CLAUDE.md files into
 * the transcript as user messages shaped `Contents of <abs-path>: …`, which is
 * configuration being handed to the agent, not a person asking for something.
 * Matched as a pattern rather than a prefix so an ask that merely opens with
 * the words "contents of" is untouched.
 */
const INJECTED_FILE = /^contents of \/\S+\s*:/;

/** A step whose whole body is one of these tags carries no ask. */
const NOISE_EXACT = new Set(["<transcript>", ""]);

/**
 * Unwrap the one-key JSON envelope transcript steps are stored in.
 *
 * User-side steps arrive as `{"user": "..."}` for something a person typed and
 * `{"<ToolName>": "..."}` for a tool result being fed back. Only the `user`
 * key can hold an ask; a `{"Bash": "..."}` step is the previous turn's output,
 * which is why tool-keyed envelopes are rejected outright rather than searched.
 */
function unwrap(raw: string): { text: string; isToolResult: boolean } {
  const trimmed = raw.trim();
  if (!trimmed.startsWith("{")) return { text: trimmed, isToolResult: false };
  let parsed: unknown;
  try {
    parsed = JSON.parse(trimmed);
  } catch {
    return { text: trimmed, isToolResult: false };
  }
  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
    return { text: trimmed, isToolResult: false };
  }
  const keys = Object.keys(parsed as Record<string, unknown>);
  if (keys.length !== 1) return { text: trimmed, isToolResult: false };
  const value = (parsed as Record<string, unknown>)[keys[0]];
  if (typeof value !== "string") return { text: trimmed, isToolResult: false };
  return { text: value.trim(), isToolResult: keys[0] !== "user" };
}

/** True when this user-step text is harness chatter rather than an ask. */
export function isNoiseStep(raw: string): boolean {
  const { text, isToolResult } = unwrap(raw);
  if (isToolResult) return true;
  const lower = text.toLowerCase();
  if (NOISE_EXACT.has(lower)) return true;
  if (INJECTED_FILE.test(lower)) return true;
  return NOISE_PREFIXES.some((p) => lower.startsWith(p));
}

/** Collapse to one line and clip on a word boundary where one is near. */
export function clipTitle(text: string, max = 120): string {
  const flat = text.replace(/\s+/g, " ").trim();
  if (flat.length <= max) return flat;
  const cut = flat.slice(0, max);
  const space = cut.lastIndexOf(" ");
  // Only respect the word boundary when it is not throwing away a third of the
  // budget; otherwise a long unbroken token would clip to almost nothing.
  return (space > max * 0.6 ? cut.slice(0, space) : cut) + "…";
}

/**
 * The session's title: the first user step that is an actual ask.
 *
 * @param userMessages raw `message` column values for the session's user-role
 *   steps, in transcript order.
 * @returns the clipped ask, or `""` when the session contains none — which is a
 *   real state (permission-hook fan-outs record one shared instruction and no
 *   human ask at all) and must not be papered over with a placeholder.
 */
export function sessionTitle(userMessages: string[], max = 120): string {
  for (const raw of userMessages) {
    if (!raw || isNoiseStep(raw)) continue;
    const { text } = unwrap(raw);
    if (!text) continue;
    return clipTitle(text, max);
  }
  return "";
}
